import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import AsideMenu from "@/components/ui/aside-menu";
import DialogProvider from "@/providers/dialog-provider";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});



export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased dark`}
      >
        <nav className="border-grid sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
          <div className="container p-3">
            <img src="./favicon.ico" alt="" className="p-3" width={80} height={80} />
          </div>
        </nav>
        <div className="container flex-1 items-start md:grid md:grid-cols-[220px_minmax(0,1fr)] md:gap-6 lg:grid-cols-[240px_minmax(0,1fr)] lg:gap-10">

          <AsideMenu />
          <main className="relative py-6 lg:gap-10 lg:py-8  ">
            {children}
            <DialogProvider />
          </main>

        </div>
      </body>
    </html>
  );
}
