import { Metadata } from 'next';
import ProductClient from './components/ProductClient';

export const metadata: Metadata = {
    title: "Product Management",
    description: "Generated by create next app",
};
const RootPage = async () => {
    // const result = await getAllProduct(0, 10);
    return <ProductClient products={[]} />
}

export default RootPage