import { getAllProduct } from '@/server-action/product.service';
import ProductClient from './components/ProductClient';
import { delay } from '@/lib/utils';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: "Product Management",
    description: "Generated by create next app",
};
const RootPage = async () => {
    // const result = await getAllProduct(0, 10);
    await delay(1000)
    return <ProductClient products={[]} />
}

export default RootPage