import { Metadata } from 'next';
import CategoryClient from './components/CategoryClient';

export const metadata: Metadata = {
  title: "Category Management",
  description: "Generated by create next app",
};
const CategoryPage = async () => {
  // await delay(1.5 * 1000)
  // const result = await getAllCategory();
  return (
    <CategoryClient
    // categories={[]}
    />
  );
};

export default CategoryPage;