import React from 'react';
import { delay } from '@/lib/utils';
import DashboardClient from './components/DashboardClient';
import { Metadata } from 'next';
import { getDashboardData } from '@/server-action/dashboard.service';

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};
const DashBoardPage = async () => {
  await delay(2000);
  const dashboard = await getDashboardData();
  return (
    <DashboardClient dashboard={dashboard} />
  );
};

export default DashBoardPage;;