import React from 'react';
import { delay } from '@/lib/utils';
import DashboardClient from './components/DashboardClient';
import { Metadata } from 'next';

type Props = {};
export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};
const DashBoardPage = async (props: Props) => {
  await delay(2000)
  return (
    <DashboardClient />
  );
};

export default DashBoardPage;;